# Generated by Django 6.0 on 2025-12-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='nombre_paciente',
        ),
        migrations.AddField(
            model_name='cita',
            name='titulo',
            field=models.CharField(default='Sin título asignado', max_length=100),
            preserve_default=False,
        ),
    ]
