# Generated by Django 6.0 on 2025-12-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_cita_motivo_remove_cita_nombre_paciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(),
        ),
    ]
