# Generated by Django 6.0 on 2025-12-06 03:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_cita_hora_alter_cita_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cita',
            name='asunto',
            field=models.CharField(default='Consulta general', max_length=200, verbose_name='Asunto de la cita'),
        ),
        migrations.AddField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='cita',
            name='nombre_paciente',
            field=models.CharField(default='Sin nombre', max_length=100, verbose_name='Nombre del paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de la cita'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default='08:00:00', verbose_name='Hora de la cita'),
        ),
    ]
