# Generated by Django 6.0 on 2025-12-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_cita_titulo_cita_asunto_cita_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha',
        ),
        migrations.AddField(
            model_name='cita',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cita',
            name='asunto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre_paciente',
            field=models.CharField(max_length=100),
        ),
    ]
