# Generated by Django 6.0 on 2025-12-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_cita_descripcion_remove_cita_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='nombre_paciente',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default='2025-12-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.CharField(default='Paciente de prueba', max_length=100),
            preserve_default=False,
        ),
    ]
